### ISSUE TITLE
sealer panic when building cluster image

### ISSUE THREAD

**Issue by zhabinecho** [sealerio/sealer#1692]
### Relevant log output?

```Shell
Pulling image: docker.io/bitnami/mysql:8.0.29-debian-10-r23
Pulling image: docker.io/bitnami/bitnami-shell :10-debian-10-r431
Pulling image: docker.io/bitnami/mysqld-exporter:0.14.0-debian-10-r75
Pulling image: docker.io/bitnami/redis:6.2.7-debian-10-r23
Pulling image: docker.io/bitnami/redis-sentinel :6.2.7-debian-10-r23
Pulling image: docker.io/bitnami/redis-exporter: 1.37.0-debian-10-r63
Pulling image: docker.io/bitnami/bitnami-shell: 10-debian-10-r432
8904a6c7c467: Download complete
e6a50b627bcb: Download complete
dbb9bc619c4f: Download complete
213ec9aee27d: Download complete
c672fbd02587: Download complete
2232dadbeacf: Download complete
6a2a8eddaea3: Download complete
76762d319f3: Download complete
ef053557858e: Download complete
92c6c9bd0d84: Downloading [====>]200.5MB/204.5MB
e992a8800eca: Download complete
133767f7d45f: Download complete
c3461af354fa: Download complete
5ee56c8db25f: Download complete
db26075ba035: Download complete
panic: runtime error: slice bounds out of range [:19] with length 0
goroutine 274 [running] :
github.com/sealerio/sealer/pkg/image/save.(*DefaultImageSaver).saveBlobs.funcZ()
/Users/huaiyou.cyz/go/src/github.com/VinceCui/sealer/pkg/image/save/save.go:311+0xb76
golang.org/x/sync/errgroup.(*Group).Go. func1()
/Users/huaiyou.cyz/go/src/github.com/VinceCui/sealer/vendor/golang.org/x/sync/errgroup/errgroup.go:57+0x67
created by golang.org/x/sync/errgroup.(*Group).Go
/Users/huaiyou.cyz/go/src/github.com/VinceCui/sealer/vendor/golang.org/x/sync/errgroup/errgroup.go:54+0x92
```

### What you expected to happen?

build success

### Other environment you want to tell us?

- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by justadogistaken** [comment]
```
	for _, blob := range blobLists {
		tmpBlob := blob
		numCh <- struct{}{}
		eg.Go(func() error {
			defer func() {
				<-numCh
			}()

			simpleDgst := string(tmpBlob)[7:19]

			_, err = blobStore.Stat(is.ctx, tmpBlob)
```
problem in at `simpleDgst := string(tmpBlob)[7:19]`.
Could you help to fix this bug? check the length of tmpBlob can solve this problem.

**Comment by YTGhost** [comment]
@justadogistaken Why length of `string(tmpBlob)` is 0, I think we need to find out the reason for this instead of just checking the length?

**Comment by justadogistaken** [comment]
@YTGhost 
For this case, the empty digest returned by distribution(registry). It may be related to some problems of manifest.
What we can do here:
(1) Check the string length. I think it's natual when we do string[x:y].
(2) Or we make sure the list does not contain empty one. (checking in getBlobList)
